version: '3.7'
services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - '5432:5432'
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/

  app:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - "8080:8080"
